jobs:
- job: 'DACPACBuild'
  pool: 
    name: DAS - Continuous Integration
    demands: Agent.OS -equals Windows_NT
  workspace:
    clean: all
  steps:
  - task: VSBuild@1
    displayName: 'Build DACPAC'
    inputs:
      solution: 'src/SFA.DAS.ProviderRegistrations.Database/SFA.DAS.ProviderRegistrations.Database.sqlproj'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'
  
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        src/**/*.dacpac
      targetFolder: '$(build.artifactstagingdirectory)/publish'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish DACPAC Artifact'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)/publish'